Add markup for FileHub.
olha-khomiakova/FileHub pull request #1
Opened 2020-12-02 21:45 UTC by olha-khomiakova

Add markup for FileHub.

2020-12-09 13:22 UTC, roman-vasilenko commented
Pre-review checklist:
- [ ] Check in HTML/CSS validators
- [ ] Test manually
- [ ] Check in supported browsers: latest Chrome, Firefox, Edge, Opera and IE11
- [ ] Do self-review

2020-12-22 21:39 UTC, roman-vasilenko requested changes
Please address the comments I left.

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/Registration.html
> +                    <input class="input form-input" type="text" id="Username" placeholder="Email"/>
Get rid of `form-input` classes, because of:
1. There is no need to have `float: left` here
2. `width: 100%` should be under the `.input` rule

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/Registration.html
> +            <label class="form-label" for="confirmPsswrd">Confirm Password</label>
`confirmPsswrd` -> `confirm-password`

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/Registration.html
> +        <div class=" row-box">
On both pages remove the leading whitespace in " row-box".

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +    font: 12px/1.4 Arial, Helvetica, sans-serif;
Set the base color and min-width to `body`.

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +    height: 71px;
We don't need these props here:
```CSS
height: 71px;
display: inline-block;
float: left;
background-color: #00000000;
```

Remove them.

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +a {
Put global styles right after the `body` rule, then place `.button`, `input`, etc., and then `.form-container`, `.logo` (from top to bottom) and so on.

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +    min-width: 465px;
What's the purpose of having the `min-width` value here?

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +    font-size: 14px;
1. `font-size: 14px;` this should be set to `body`.
2. Use shorthand for padding/margin values -> `padding: 16px 20px 20px;`

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +    font-size: 22px;
Apply `font-size: 22px;` to `h1` via `.head h1` selector.

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +.title {
As mentioned before, remove the `title` div and its styles.
In case, of having the user icon positioned absolute, set the corresponding right padding in the `.head` rule to protect the title text from overlapping with icon.

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +    background: inherit;
1. Use `display: block;` instead of `float: left` to make the element apply vertical padding/margin styles
2. Remove `background: inherit;`. It's not needed here.
3. Use shorthand for colors -> `#f00`

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +    float: left;
1. Don't use `float` without a specific need. 
2. `max-width: 100px;` let's remove it
3. `#ffffff` -> `#fff`

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +.button:focus{
Add some hover styles for the button.

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +.glyphicon {
Move this style to the top and place after the global styles.

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +.glyphicon:hover {
In which case do we need this hover style?

2020-12-22 21:39 UTC, roman-vasilenko commented on markup/css/style.css
> +.table td {
The explorer page related styles will be reviewed in the next PR with the table implemented.

2020-12-27 18:41 UTC, olha-khomiakova commented on markup/Registration.html
> +<div class="form-container">
Done.

2020-12-27 18:46 UTC, olha-khomiakova commented on markup/Registration.html
> +    <div class="row-box">
Done.

2020-12-27 19:04 UTC, olha-khomiakova commented on markup/Registration.html
> +            <div class="title">
Done.

2020-12-27 19:09 UTC, olha-khomiakova commented on markup/Registration.html
> +                <span class="glyphicon glyphicon-user form-icon" aria-hidden="true"></span>
Done.

2020-12-27 19:11 UTC, olha-khomiakova commented on markup/Registration.html
> +            <span class="right">
Done.

2020-12-27 19:13 UTC, olha-khomiakova commented on markup/Registration.html
> +                    <input class="input form-input" type="text" id="Username" placeholder="Email"/>
Done.

2020-12-27 19:17 UTC, olha-khomiakova commented on markup/Registration.html
> +                    <input class="input form-input" type="text" id="Username" placeholder="Email"/>
Done.

2020-12-27 19:18 UTC, olha-khomiakova commented on markup/Registration.html
> +            <label class="form-label" for="confirmPsswrd">Confirm Password</label>
Done.

2020-12-27 19:20 UTC, olha-khomiakova commented on markup/Registration.html
> +        <div class=" row-box">
Done.

2020-12-27 19:23 UTC, olha-khomiakova commented on markup/css/style.css
> +    font: 12px/1.4 Arial, Helvetica, sans-serif;
Done.

2020-12-27 19:26 UTC, olha-khomiakova commented on markup/css/style.css
> +    height: 71px;
Done.

2020-12-27 19:33 UTC, olha-khomiakova commented on markup/css/style.css
> +a {
Done.

2020-12-27 19:36 UTC, olha-khomiakova commented on markup/css/style.css
> +    min-width: 465px;
Realized that it makes no sense. Removed it.

2020-12-27 19:39 UTC, olha-khomiakova commented on markup/css/style.css
> +    font-size: 14px;
Ok, done.

2020-12-27 19:40 UTC, olha-khomiakova commented on markup/css/style.css
> +    font-size: 22px;
Done.

2020-12-27 19:49 UTC, olha-khomiakova commented on markup/css/style.css
> +.title {
Done.

2020-12-27 19:51 UTC, olha-khomiakova commented on markup/css/style.css
> +    background: inherit;
Done.

2020-12-27 19:52 UTC, olha-khomiakova commented on markup/css/style.css
> +    float: left;
Done.

2020-12-27 19:56 UTC, olha-khomiakova commented on markup/css/style.css
> +.button:focus{
Done.

2020-12-27 19:58 UTC, olha-khomiakova commented on markup/css/style.css
> +.glyphicon {
Done.

2020-12-27 20:08 UTC, olha-khomiakova commented on markup/css/style.css
> +.glyphicon:hover {
I was adding a style change from another branch. I removed it from here and change the styles in another branch so that it doesn't exist either.

2020-12-27 20:14 UTC, olha-khomiakova commented on markup/css/style.css
> +.table td {
Ок.

2020-12-29 16:54 UTC, roman-vasilenko commented on markup/Registration.html
> +    <div class="row-box">
1. Move `<div class="head">` out of the `<form>` since it's not a part of the form block.
2. `<div class="head">...</div>` -> `<header class="head">...</header>`.
3. `<main class="container">...</main>` - this should be a `<div>` element. Use `<main>` as wrapper for the form content.

2020-12-29 16:59 UTC, roman-vasilenko commented on markup/css/style.css
> +    font: 12px/1.4 Arial, Helvetica, sans-serif;
`color: #000000;` -> `color: #000;`

2020-12-29 17:02 UTC, roman-vasilenko commented on markup/css/style.css
> +a {
Put the global link styles after the `body` rule:
```
a {
    color: #6ab3ea;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}
```

2020-12-29 17:07 UTC, roman-vasilenko commented on markup/css/style.css
> +.glyphicon {
Change the selector to `.head .glyphicon-user` so these custom styles will be applied only in this specific context.

2020-12-29 17:22 UTC, roman-vasilenko requested changes
Please address the comments I left.

2020-12-29 17:22 UTC, roman-vasilenko commented on markup/css/style.css
> +footer {
1. Do not apply footer styles globally
2. Move it to the bottom of the file

2020-12-29 17:22 UTC, roman-vasilenko commented on markup/css/style.css
> +    width: 100%;
I don't see the next styles to be required here:
```
width: 100%;
word-wrap: break-word;
display: inline-block;
```

Please remove them and let me know if there are any issues.

2020-12-29 17:22 UTC, roman-vasilenko commented on markup/Authentication.html
> +                <button class="button" type="submit">Log In</button>
Add `title` attributes for clickable elements such as `<button>` and `<a>`:
1. `<button class="button" type="submit" title="Log In">Log In</button>`
2. `<a class="form-link" href="#" title="Don't have an account yet?">Don't have an account yet?</a>`

Make the change on both pages.

2021-01-04 11:17 UTC, olha-khomiakova commented on markup/Registration.html
> +    <div class="row-box">
Done.

2021-01-04 11:22 UTC, olha-khomiakova commented on markup/css/style.css
> +a {
Done.

2021-01-04 11:31 UTC, olha-khomiakova commented on markup/css/style.css
> +    font: 12px/1.4 Arial, Helvetica, sans-serif;
Done.

2021-01-04 11:32 UTC, olha-khomiakova commented on markup/css/style.css
> +footer {
Done.

2021-01-04 11:35 UTC, olha-khomiakova commented on markup/css/style.css
> +    width: 100%;
If the title is very long and without spaces, then it will be outside the form.

2021-01-04 11:47 UTC, olha-khomiakova commented on markup/Authentication.html
> +                <button class="button" type="submit">Log In</button>
Done.

2021-01-04 12:05 UTC, olha-khomiakova commented on markup/css/style.css
> +    width: 100%;
But if it's ok, I've removed those styles.

2021-01-04 20:37 UTC, roman-vasilenko commented on markup/Authentication.html
> +                <button class="button" type="submit">Log In</button>
The title values should duplicate the text content:

```
<a class="form-link" title="Go to the registration page" href="#">Don't have an account yet?</a>
```

=>

```
<a class="form-link" title="Don't have an account yet?" href="#">Don't have an account yet?</a>
```

Check on both pages.

2021-01-04 20:43 UTC, roman-vasilenko requested changes
Please address the latest comments.

2021-01-04 20:43 UTC, roman-vasilenko commented on markup/css/style.css
> +    background-color: #6C89CC;
`#6C89CC`-> `#6c89cc`

2021-01-04 20:43 UTC, roman-vasilenko commented on markup/css/style.css
> +.glyphicon-user {
Don't apply these styles for every user icon so change the selector to `.head .glyphicon-user` and put this rule closely to `.head` related styles.

2021-01-04 21:09 UTC, roman-vasilenko approved these changes
LGTM

2021-01-04 21:24 UTC, merged