feature/titleService
olha-khomiakova/FileHub pull request #14
Opened 2021-01-13 09:12 UTC by olha-khomiakova

Add TitleService, which changes title. Now, when going to pages, the title changes, which the user can see in the title of the tab and history.

2021-01-18 11:58 UTC, dkalinin requested changes
PTAL

2021-01-18 11:58 UTC, dkalinin commented on js/app/login/login-page/index.js
> +   * @inheritDoc
This method is not inherited.

2021-01-18 11:58 UTC, dkalinin commented on js/app/services/title-service/index.js
> +   * Saves document and application name.
This is a description of implementation details. This should be hidden from users.

2021-01-18 11:58 UTC, dkalinin commented on js/app/services/title-service/index.js
> +    console.log(titleElement);
Please remove.

2021-01-18 11:58 UTC, dkalinin commented on js/tests/app/services/title-service/index.js
> +  test('validation input should be rendered with certain data', function(assert) {
Please fix this name, also check others.

2021-01-19 22:15 UTC, dkalinin requested changes

2021-01-19 22:15 UTC, dkalinin commented on js/tests/app/login/login-page/index.js
> +        const mss = [];
What is mss?

2021-01-19 23:04 UTC, olha-khomiakova commented on js/tests/app/login/login-page/index.js
> +        const mss = [];
This is the array in which the Title will be. It is an array because document.getElementsByTagName() returns an array of elements. The name of the mss has been changed.

2021-01-21 08:45 UTC, dkalinin approved these changes
Please fix and merge.

2021-01-21 08:45 UTC, dkalinin commented on js/app/registration/registration-page/index.js
> +    console.log('ddd');
Please remove.

2021-01-21 08:45 UTC, dkalinin commented on js/tests/app/login/login-page/index.js
> +        return arrayWithHtmlElement;
Can be simplified:
```js
this.title = document.createElement(qualifiedName);
return [this.title];
```
This shows that there's no need to have array except in order to return an array with a new element.

2021-01-21 08:45 UTC, dkalinin commented on js/app/registration/registration-form/index.js
> +          if (results.some((promise) => promise.status === 'rejected')) {
If there's a long condition then it's more readable to have a local variable:
```js
const hasRejectedPromises = results.some((promise) => promise.status === 'rejected')
if(hasRejectedPromises) {
...

2021-01-21 17:30 UTC, merged