feature/fetch
olha-khomiakova/FileHub pull request #15
Opened 2021-01-13 11:54 UTC by olha-khomiakova

2021-01-21 13:38 UTC, dkalinin requested changes

2021-01-24 17:48 UTC, dkalinin requested changes
PTAL

2021-01-24 17:48 UTC, dkalinin commented on js/app/login/login-form/index.js
> +    Array.from(this._container.getElementsByClassName('error-message'))
Only ValidatableInput knows about this class name. We shouldn't use it, only public fields/inputs of ValidatableInput component.

2021-01-24 17:48 UTC, dkalinin commented on js/app/registration/registration-form/index.js
> +    Array.from(this._container.getElementsByClassName('error-message'))
The same. Use ValidatableInput API.

2021-01-24 17:48 UTC, dkalinin commented on js/app/registration/registration-page/index.js
> +            }
Let's have different methods for general server error and server validation error.

2021-01-24 17:48 UTC, dkalinin commented on js/app/services/api-service/index.js
> +        .catch((errors) => {
Is this indent correct?

2021-01-24 17:48 UTC, dkalinin commented on js/app/services/api-service/index.js
> +      if (response.status.toString() === ('422')) {
Why is `toString()` needed? Can we compare with number?

2021-01-24 17:48 UTC, dkalinin commented on js/app/services/api-service/index.js
> +      } else if (response.status.toString().startsWith('4')) {
Let's handle as a number.

2021-01-24 17:48 UTC, dkalinin commented on js/app/services/api-service/index.js
> +      } else if (response.status.toString().startsWith('5')) {
Let's handle as a number.

2021-01-24 17:48 UTC, dkalinin commented on js/app/services/api-service/index.js
> +            .map((error)=> new ServerValidationErrorJson(error.field, error.message)));
Let's move this logic to ValidationErrorResponse's constructor.

2021-01-24 17:48 UTC, dkalinin commented on js/app/services/api-service/index.js
> +class ServerValidationErrorJson {
This is not needed here. Let's move to errors.

2021-01-24 17:48 UTC, dkalinin commented on js/tests/app/login/login-page/index.js
> +import {devFetch} from '../../../../app/services/dev-fetch';
devFetch is for development only. Do not use it in tests.

2021-01-24 17:48 UTC, dkalinin commented on js/tests/app/login/login-page/index.js
>  import {ApiService} from '../../../../app/services/api-service';
Let's use ApiService mock instead of the real ApiService.

2021-01-24 17:48 UTC, dkalinin commented on js/tests/app/services/api-service/index.js
> +import {devFetch} from '../../../../app/services/dev-fetch';
devFetch is for development only. Do not use it in tests. It can be replaced with mock fetch in this test module.

2021-01-25 20:42 UTC, dkalinin requested changes
PTAL

2021-01-25 20:42 UTC, dkalinin commented on js/app/login/login-form/index.js
> +  _cleanHTMLElementForErrorMessage() {
Since we are not using HTMLElements let's rename to `_cleanErrorMessages`.

2021-01-25 20:42 UTC, dkalinin commented on js/app/registration/registration-form/index.js
> +  }
We use setters instead of set... methods.

2021-01-25 20:42 UTC, dkalinin commented on js/app/registration/registration-form/index.js
> +  _cleanHTMLElementForErrorMessage() {
Let's rename.

2021-01-25 20:42 UTC, dkalinin commented on js/app/services/api-service/index.js
> +      console.groupEnd();
This logging should be done in dev-fetch.

2021-01-25 20:42 UTC, dkalinin commented on js/app/services/api-service/index.js
> +      console.groupEnd();
This logging should be done in dev-fetch.

2021-01-25 20:42 UTC, dkalinin commented on js/app/services/dev-fetch/index.js
> +  return Promise.resolve(responseData(init));
Please log responseData(init)

2021-01-25 20:42 UTC, dkalinin commented on js/tests/app/login/login-page/index.js
> +      title: undefined,
This field is not needed.

2021-01-25 20:42 UTC, dkalinin commented on js/tests/app/login/login-page/index.js
>      const inputs = root.querySelectorAll('input');
Let's use data- attributes.

2021-01-25 20:42 UTC, dkalinin commented on js/tests/app/login/login-page/index.js
> +        if (name === 'admin' || password === 'Admin123!') {
Why do we check it in the mock?

2021-01-25 20:42 UTC, dkalinin commented on js/tests/app/login/login-page/index.js
> +  test('Should an error message from the server be empty.', (assert) => {
Sounds like a question.
Should be smth like "Should call authenticated callback when successfully authenticated."

2021-01-25 20:42 UTC, dkalinin commented on js/tests/app/registration/registration-page/index.js
> +  test('Should be an error message from the server that comes with a status code 500.', (assert) => {
Should show an error message...

2021-01-25 20:42 UTC, dkalinin commented on js/tests/app/registration/registration-page/index.js
>        title: undefined,
Why is this needed?

2021-01-25 20:42 UTC, dkalinin commented on js/tests/app/services/api-service/index.js
> +          if (data.username === 'admin' && data.password === 'Admin123!') {
Instead of having this complicated logic just return an expected json from fetch for a specific test case.

2021-01-25 20:42 UTC, dkalinin commented on js/tests/app/services/dev-fetch/index.js
> +module('dev-fetch', function(hooks) {
dev-fetch shouldn't be tested.

2021-01-27 22:11 UTC, dkalinin requested changes
PTAL

2021-01-27 22:11 UTC, dkalinin commented on js/app/services/api-service/index.js
> +        return Promise.reject(new ServerErrorResponse(response.message));
Let's replace with 
```js 
throw new ServerErrorResponse(response.message)

2021-01-27 22:11 UTC, dkalinin commented on js/app/services/api-service/index.js
> +    });
This doesn't make sense.

2021-01-27 22:11 UTC, dkalinin commented on js/app/services/api-service/index.js
> +      }
This logic is basically the same for all requests. Can be moved to a separate method.

2021-01-27 22:11 UTC, dkalinin commented on js/app/services/api-service/index.js
> +    });
This is not needed.

2021-01-27 22:11 UTC, dkalinin commented on js/app/services/error-responses/index.js
> + * A data structure that stores array with ServerValidationError.
This is not a data structure but an error that corresponds to the invalid entered data.

2021-01-27 22:11 UTC, dkalinin commented on js/tests/app/registration/registration-page/index.js
> +        return Promise.reject(new ValidationErrorResponse(errors));
There's no need to use push:
```js
const errors = [
        {
          field: 'username',
          message: 'Username should be less than 12 characters.',
        },
        {
          field: 'password',
          message: 'Password should be less than 15 characters.',
        }
]

2021-01-27 22:11 UTC, dkalinin commented on js/tests/app/services/api-service/index.js
> +            assert.strictEqual(data.password, 'Admin123!', 'Password should be the same as provided from the outside.');
Could be replaced with 
```js
 assert.strictEqual(init.body, JSON.stringify({username:'serverError', password:'Admin123'}), 'Should...')

2021-01-28 01:36 UTC, olha-khomiakova commented on js/app/services/api-service/index.js
> +        return Promise.reject(new ServerErrorResponse(response.message));
Done.

2021-01-28 01:36 UTC, olha-khomiakova commented on js/app/services/api-service/index.js
> +    });
Removed.

2021-01-28 01:37 UTC, olha-khomiakova commented on js/app/services/api-service/index.js
> +      }
Moved.

2021-01-28 01:37 UTC, olha-khomiakova commented on js/app/services/api-service/index.js
> +    });
Removed.

2021-01-28 01:39 UTC, olha-khomiakova commented on js/app/services/error-responses/index.js
> + * A data structure that stores array with ServerValidationError.
Done.

2021-01-28 01:40 UTC, olha-khomiakova commented on js/tests/app/registration/registration-page/index.js
> +        return Promise.reject(new ValidationErrorResponse(errors));
Done.

2021-01-28 02:06 UTC, olha-khomiakova commented on js/tests/app/services/api-service/index.js
> +            assert.strictEqual(data.password, 'Admin123!', 'Password should be the same as provided from the outside.');
Done.

2021-01-28 09:29 UTC, dkalinin approved these changes

2021-01-28 14:53 UTC, merged