feature/file-list-page
olha-khomiakova/FileHub pull request #16
Opened 2021-01-22 09:16 UTC by olha-khomiakova

Render the file list page. Create components like this:

2021-01-25 21:06 UTC, dkalinin commented
@olha-khomiakova please fix the conflicts.

2021-01-28 10:37 UTC, dkalinin requested changes
PTAL

2021-01-28 10:37 UTC, dkalinin commented on js/app/file-list-page/file-list-item/index.js
> +    }
Let's show `0 B` or `5 B` if size is less than 1024.

2021-01-28 10:37 UTC, dkalinin commented on js/app/file-list-page/file-list/index.js
> +    if (firstItem.constructor.name === secondItem.constructor.name) {
Let's use type field instead.

2021-01-28 10:37 UTC, dkalinin commented on js/app/file-list-page/link-with-action/index.js
> +    this.handller= handler;
Please reformat code.

2021-01-28 10:37 UTC, dkalinin commented on js/app/file-list-page/link-with-action/index.js
> +    });
Let's use https://developer.mozilla.org/en-US/docs/Web/API/Element/className which doesn't need the class string to be split by spaces.

2021-01-28 17:01 UTC, olha-khomiakova commented on js/app/components/button/index.js
> +  addEvent(handler) {
Done.

2021-01-28 17:06 UTC, olha-khomiakova commented on js/app/components/button/index.js
> +      this.handller();
Made a check.

2021-01-28 17:16 UTC, olha-khomiakova commented on js/app/components/component/index.js
> +    if (markup.substring(0, markup.indexOf('>')+1).trim() === '<tr>') {
Done.

2021-01-28 17:21 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-item/index.js
> +    }
Done.

2021-01-28 17:34 UTC, olha-khomiakova commented on js/app/file-list-page/file-list/index.js
> +    if (firstItem.constructor.name === secondItem.constructor.name) {
Done.

2021-01-28 17:35 UTC, olha-khomiakova commented on js/app/file-list-page/link-with-action/index.js
> +    this.handller= handler;
Done.

2021-01-28 20:14 UTC, olha-khomiakova commented on js/app/file-list-page/link-with-action/index.js
> +    });
Done.

2021-02-03 22:19 UTC, dkalinin approved these changes
![image](https://user-images.githubusercontent.com/11214435/106816754-80ef2200-667e-11eb-9c4a-c90a15e8859a.png)
Let's be consistent with the upper case:
"Create new directory"
"Upload file"
Please merge after fix.

2021-02-05 13:33 UTC, merged