feature/folder-requests
olha-khomiakova/FileHub pull request #17
Opened 2021-01-26 22:15 UTC by olha-khomiakova

Implement the ability to send requests to the server to get the user preferences, the data of a specific folder, the content of a specific folder.

2021-02-04 21:20 UTC, dkalinin requested changes
PTAL

2021-02-04 21:20 UTC, dkalinin commented on js/app/services/api-service/index.js
> +      return Promise.resolve(new FolderListModel(json));
It is not necessary return a promise from `then`. You can return any value. If it returns promise then the next `then` will receive a result of this `then`.

2021-02-04 21:20 UTC, dkalinin commented on js/app/services/api-service/index.js
> +    return this._window.fetch(`/folder/00000/content`, {
`id` should be used instead of `000000`.

2021-02-04 21:20 UTC, dkalinin commented on js/app/services/api-service/index.js
>        }
What if status code is 400?

2021-02-04 21:20 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +        this._serverError = error.message;
Breadcrumbs component should show error state.

2021-02-04 21:20 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +        this._serverError = error.message;
FileList component should show error state.

2021-02-04 21:20 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +      this._serverError = error.message;
Message should say that it was unable to load user preferences.

2021-02-05 13:36 UTC, olha-khomiakova commented on js/app/services/api-service/index.js
> +      return Promise.resolve(new FolderListModel(json));
Done.

2021-02-05 13:38 UTC, olha-khomiakova commented on js/app/services/api-service/index.js
> +    return this._window.fetch(`/folder/00000/content`, {
Done.

2021-02-05 14:03 UTC, olha-khomiakova commented on js/app/services/api-service/index.js
>        }
Done.

2021-02-05 14:33 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +        this._serverError = error.message;
Done.

2021-02-05 14:33 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +        this._serverError = error.message;
Done.

2021-02-05 14:34 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +      this._serverError = error.message;
Done.

2021-02-07 21:14 UTC, dkalinin approved these changes
Please add dev-fetch logging and tests to check hoe error message is rendered for each API call.

2021-02-07 21:14 UTC, dkalinin commented on js/app/file-list-page/breadcrumbs/index.js
> +   * Sets an error massage.
M*a*ssage is good, but m*e*ssage fits better.

2021-02-07 21:14 UTC, dkalinin commented on js/app/services/api-service/index.js
> +   * @param {Object} errorMessages
Please add description. Also it's better to specify possible keys.

2021-02-07 21:14 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +        this._breadcrumbs.setErrorMessage();
Why don't we pass message here?

2021-02-07 21:14 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +        this._fileList.setErrorMessage();
Why don't we pass message here?

2021-02-07 21:14 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +      this._fileList.setErrorMessage();
One error message is enough here.

2021-02-07 22:02 UTC, olha-khomiakova commented on js/app/file-list-page/breadcrumbs/index.js
> +   * Sets an error massage.
Done.

2021-02-07 22:13 UTC, olha-khomiakova commented on js/app/services/api-service/index.js
> +   * @param {Object} errorMessages
Done.

2021-02-07 22:23 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +        this._breadcrumbs.setErrorMessage();
Done.

2021-02-07 22:23 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +        this._fileList.setErrorMessage();
Done.

2021-02-07 22:24 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +      this._fileList.setErrorMessage();
Done.

2021-02-07 23:38 UTC, merged