Сonvert components to state components.
olha-khomiakova/FileHub pull request #18
Opened 2021-02-02 15:45 UTC by olha-khomiakova

2021-02-07 21:54 UTC, dkalinin approved these changes

2021-02-07 22:56 UTC, dkalinin requested changes

2021-02-07 22:56 UTC, dkalinin commented on js/app/components/component/index.js
>      this.addEventListeners();
Please move this to init

2021-02-07 22:58 UTC, dkalinin requested changes

2021-02-07 22:58 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +    this._initNestedComponentsWithDataFromServer().then();
Let's use init method instead of overriding constructor.

2021-02-08 10:03 UTC, olha-khomiakova commented on js/app/components/component/index.js
>      this.addEventListeners();
Done.

2021-02-08 10:04 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +    this._initNestedComponentsWithDataFromServer().then();
Done.

2021-02-08 19:49 UTC, dkalinin requested changes
PTAL

2021-02-08 19:49 UTC, dkalinin commented on js/app/components/component/index.js
> +    this.init(params);
You can use `this.init(...params)`

2021-02-08 19:49 UTC, dkalinin commented on js/app/components/component/index.js
> +    this.addEventListeners();
Please read the documentation and adjust init behavior properly.

2021-02-08 19:49 UTC, dkalinin commented on js/app/components/form/index.js
> +    this.init();
Init should be called once — during initialization of a component.

2021-02-08 19:49 UTC, dkalinin commented on js/app/components/form/index.js
>      inputsCreator(this.getElement('inputs'));
This should not be called here but should re-render the component.

2021-02-09 06:46 UTC, olha-khomiakova commented on js/app/components/form/index.js
>      inputsCreator(this.getElement('inputs'));
Done.

2021-02-09 06:46 UTC, olha-khomiakova commented on js/app/components/form/index.js
> +    this.init();
Done.

2021-02-09 06:46 UTC, olha-khomiakova commented on js/app/components/component/index.js
> +    this.addEventListeners();
Refactor.

2021-02-09 07:38 UTC, olha-khomiakova commented on js/app/components/component/index.js
> +    this.init(params);
Done.

2021-02-09 11:04 UTC, dkalinin requested changes
PTAL

2021-02-09 11:04 UTC, dkalinin commented on js/app/services/dev-fetch/index.js
> +/* eslint-disable no-debugger, no-console */
Please remove no-debugger.

2021-02-09 11:04 UTC, dkalinin commented on js/tests/app/file-list-page/file-list-page/index.js
>          return Promise.resolve({username: 'test', rootFolderId: '00000'});
Let's replace '00000' with local variable.

2021-02-09 11:35 UTC, olha-khomiakova commented on js/app/components/component/index.js
> +   * Initializes the component and provides the required services.
Done.

2021-02-09 11:41 UTC, olha-khomiakova commented on js/app/file-list-page/breadcrumbs/index.js
> +                            <span data-fh="crumbs" ${this._iconClass || `class = "${this._classForErrorMessage}"`}>
Changed this._iconClass to this._classForErrorMessage.

2021-02-09 14:39 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +  _initNestedComponentsWithDataFromServer() {
Done.

2021-02-09 14:40 UTC, olha-khomiakova commented on js/app/services/dev-fetch/index.js
> +/* eslint-disable no-debugger, no-console */
Done.

2021-02-09 14:49 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-item/index.js
> +  init(...params) {
Done.

2021-02-09 14:59 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-item/index.js
> +  }
Done.

2021-02-09 16:49 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-item/index.js
> +         <td data-fh="size" class="fourth-column">${this._convertSize()}</td>
Done.

2021-02-09 16:52 UTC, olha-khomiakova commented on js/tests/app/file-list-page/file-list-page/index.js
>          return Promise.resolve({username: 'test', rootFolderId: '00000'});
Done.

2021-02-09 19:08 UTC, dkalinin requested changes

2021-02-09 19:08 UTC, dkalinin commented on js/app/file-list-page/file-list/index.js
>    addList(list) {
Let's replace with setter for "items" field.

2021-02-09 19:08 UTC, dkalinin commented on js/app/file-list-page/file-list/index.js
> +    this._classForErrorMessage = null;
Why are we doing it here? They have their setters.

2021-02-09 19:08 UTC, dkalinin commented on js/app/file-list-page/file-list/index.js
>      this._message = 'Unable to load a file list.';
How about `errorMessage`?

2021-02-09 19:08 UTC, dkalinin commented on js/app/file-list-page/file-list/index.js
> +    this._list = null;
Please remove. It's not a responsibility of errorMessage setter.

2021-02-09 19:08 UTC, dkalinin commented on js/app/file-list-page/file-list/index.js
> +      this._list.listItemModel.sort(this._sortByTypeAndName);
Why not `this._list.sort(...)` ?

2021-02-09 19:08 UTC, dkalinin commented on js/app/file-list-page/link-with-action/index.js
> +    super.init();
...params are ignored.
Are they needed?

2021-02-09 19:08 UTC, dkalinin commented on js/app/login/login-form/index.js
> +    super.init();
...params ignored.

2021-02-09 19:08 UTC, dkalinin commented on js/app/registration/registration-form/index.js
> +    super.init();
...params ignored.

2021-02-09 19:08 UTC, dkalinin commented on js/tests/app/file-list-page/breadcrumbs/index.js
> +  test('Should render breadcrumbs with certain data.', function(assert) {
iconClass field is not tested. Please check all public fields of each component.

2021-02-09 20:17 UTC, olha-khomiakova commented on js/app/components/form/index.js
> +  init(...params) {
Done.

2021-02-09 20:18 UTC, olha-khomiakova commented on js/app/components/validatable-input/index.js
> +    this._id = createAUniqueId();
Done.

2021-02-09 20:18 UTC, olha-khomiakova commented on js/app/file-list-page/breadcrumbs/index.js
>    init(...params) {
Done.

2021-02-09 20:22 UTC, olha-khomiakova commented on js/app/file-list-page/file-list/index.js
>    addList(list) {
Done.

2021-02-09 20:23 UTC, olha-khomiakova commented on js/app/file-list-page/file-list/index.js
> +    this._classForErrorMessage = null;
Done.

2021-02-09 20:24 UTC, olha-khomiakova commented on js/app/file-list-page/file-list/index.js
> +    this._list = null;
Done.

2021-02-09 20:25 UTC, olha-khomiakova commented on js/app/file-list-page/file-list/index.js
> +      this._list.listItemModel.sort(this._sortByTypeAndName);
Done.

2021-02-09 20:26 UTC, olha-khomiakova commented on js/app/file-list-page/link-with-action/index.js
> +    super.init();
Done.

2021-02-09 20:26 UTC, olha-khomiakova commented on js/app/login/login-form/index.js
> +    super.init();
Done.

2021-02-09 20:27 UTC, olha-khomiakova commented on js/app/registration/registration-form/index.js
> +    super.init();
Done.

2021-02-09 20:58 UTC, olha-khomiakova commented on js/app/file-list-page/breadcrumbs/index.js
> +                            `class = "${this._classForErrorMessage}"`}>${this._breadcrumbs}</span>
Done.

2021-02-09 21:08 UTC, olha-khomiakova commented on js/app/file-list-page/file-list/index.js
>      this._message = 'Unable to load a file list.';
Done.

2021-02-09 21:13 UTC, olha-khomiakova commented on js/tests/app/file-list-page/breadcrumbs/index.js
> +  test('Should render breadcrumbs with certain data.', function(assert) {
I haven`t iconClass field in Breadcrumbs.

2021-02-10 22:23 UTC, dkalinin approved these changes
Please fix and merge.

2021-02-10 22:23 UTC, dkalinin commented on js/app/file-list-page/file-list/index.js
> +  }
Please remove.

2021-02-11 13:31 UTC, olha-khomiakova commented on js/app/file-list-page/file-list/index.js
> +  }
Done.

2021-02-11 13:31 UTC, merged