Add application state and service that manage it.
olha-khomiakova/FileHub pull request #19
Opened 2021-02-03 11:20 UTC by olha-khomiakova

2021-02-09 19:45 UTC, dkalinin requested changes
PTAL

2021-02-09 19:45 UTC, dkalinin commented on js/app/application/index.js
> +    this._stateService = new StateService(state, this._apiService, actions);
Mutators also should be set in constructor.

2021-02-09 19:45 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +import {actionNames} from '../../services/state-service/actions';
Since actionNames is an enum let's rename it to `ActionName`

2021-02-09 19:45 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +    });
Why?

2021-02-09 19:45 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +      });
Why do we need empty catch?

2021-02-09 19:45 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +      }
Why is if-else here? Can't we set error and username simultaneously?

2021-02-09 19:45 UTC, dkalinin commented on js/app/file-list-page/file-list-page/index.js
> +  init(titleService, stateService) {
Please change JSDoc.

2021-02-09 19:45 UTC, dkalinin commented on js/app/file-list-page/file-list/index.js
> +  init(...params) {
Params are not needed here.

2021-02-09 19:45 UTC, dkalinin commented on js/app/services/state-service/actions/actions.js
> +import {mutators} from '../mutators';
Please change actionNames and mutatorNames names to enum style: https://google.github.io/styleguide/jsguide.html#naming-enum-names

2021-02-09 19:45 UTC, dkalinin commented on js/app/services/state-service/state/index.js
> +  userDetails: new UserPreferences({name: '', id: '', rootFolderId: '', type: ''}),
Why?

2021-02-09 19:45 UTC, dkalinin commented on js/app/services/state-service/state/index.js
> +  currentFolder: new FolderListModel({id: '', name: '', itemAmount: '', parentId: '', type: ''}),
Why?

2021-02-09 19:45 UTC, dkalinin commented on js/app/services/state-service/state/index.js
> +  fileList: new ListItemModel([]),
There should be no ListItemModel but array of models.

2021-02-09 19:45 UTC, dkalinin commented on js/tests/app/file-list-page/file-list-page/index.js
> +          ];
Why are we returning data here? We need just check that proper actions were called. 
And check that state is rendered properly.

2021-02-09 19:45 UTC, dkalinin commented on js/tests/app/services/state-service/actions/index.js
> +      assert.ok(true, 'Should call a callback.');
Please check params here and in other acton tests.

2021-02-09 19:45 UTC, dkalinin commented on js/tests/app/services/state-service/actions/index.js
> +      assert.ok(true, 'Should call a callback.');
Should be `assert.step('mutate');`

2021-02-09 19:45 UTC, dkalinin commented on js/tests/app/services/state-service/mutators/index.js
> +
Let's have separate tests for each mutator.

2021-02-09 19:45 UTC, dkalinin commented on js/tests/app/services/state-service/index.js
> +import {actionNames} from '../../../../app/services/state-service/actions';
Let's not use real action names here. Just create some for testing.

2021-02-09 19:45 UTC, dkalinin commented on js/tests/app/services/state-service/index.js
> +    done();
Done is not needed.

2021-02-10 05:32 UTC, olha-khomiakova commented on js/app/application/index.js
> +    // state.userDetails = null;
Done.

2021-02-10 05:35 UTC, olha-khomiakova commented on js/app/application/index.js
> +    this._stateService = new StateService(state, this._apiService, actions);
Done.

2021-02-10 05:36 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +import {actionNames} from '../../services/state-service/actions';
Done.

2021-02-10 05:37 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +    });
Delete.

2021-02-10 05:38 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +      });
Delete.

2021-02-10 05:48 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +      }
If I set the error message, then the class is set to span, which shows that this is an error.

2021-02-10 05:50 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +  init(titleService, stateService) {
Done.

2021-02-10 05:50 UTC, olha-khomiakova commented on js/app/file-list-page/file-list/index.js
> +  init(...params) {
Done.

2021-02-10 06:03 UTC, olha-khomiakova commented on js/app/services/state-service/actions/actions.js
> +import {mutators} from '../mutators';
Done.

2021-02-10 06:17 UTC, olha-khomiakova commented on js/app/services/state-service/state/index.js
> +  currentFolder: new FolderListModel({id: '', name: '', itemAmount: '', parentId: '', type: ''}),
Since there is no proxy yet, I need to check in each licenser which fields can be updated. Added check whether the required field is set in the state. And in a branch with a proxy, I'll just sign each field for the desired state change. Checks will be removed.

2021-02-10 06:17 UTC, olha-khomiakova commented on js/app/services/state-service/state/index.js
> +  userDetails: new UserPreferences({name: '', id: '', rootFolderId: '', type: ''}),
Since there is no proxy yet, I need to check in each licenser which fields can be updated. Added check whether the required field is set in the state. And in a branch with a proxy, I'll just sign each field for the desired state change. Checks will be removed.

2021-02-10 06:22 UTC, olha-khomiakova commented on js/app/services/state-service/state/index.js
> +  fileList: new ListItemModel([]),
Done.

2021-02-10 08:22 UTC, olha-khomiakova commented on js/tests/app/services/state-service/actions/index.js
> +      assert.ok(true, 'Should call a callback.');
Done.

2021-02-10 08:28 UTC, olha-khomiakova commented on js/tests/app/services/state-service/actions/index.js
> +      assert.ok(true, 'Should call a callback.');
Done.

2021-02-10 08:32 UTC, olha-khomiakova commented on js/tests/app/services/state-service/mutators/index.js
> +
Done.

2021-02-10 08:35 UTC, olha-khomiakova commented on js/tests/app/services/state-service/index.js
> +import {actionNames} from '../../../../app/services/state-service/actions';
Done.

2021-02-10 08:36 UTC, olha-khomiakova commented on js/tests/app/services/state-service/index.js
> +    done();
Done.

2021-02-10 09:05 UTC, olha-khomiakova commented on js/app/services/state-service/state/index.js
> +  userDetails: new UserPreferences({name: '', id: '', rootFolderId: '', type: ''}),
Changed to regular objects. There must be a name field in them, otherwise an error will be thrown.

2021-02-10 09:05 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +      }
Done.

2021-02-10 09:05 UTC, olha-khomiakova commented on js/app/services/state-service/state/index.js
> +  currentFolder: new FolderListModel({id: '', name: '', itemAmount: '', parentId: '', type: ''}),
Changed to regular objects. There must be a name field in them, otherwise an error will be thrown.

2021-02-10 09:07 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +    });
Because I need to throw an error if userDetails did not load, otherwise there will be a request for the following components.

2021-02-10 09:29 UTC, olha-khomiakova commented on js/tests/app/file-list-page/file-list-page/index.js
> +          ];
I set this data to a state in order to check later how the page will render a fileList with items.

2021-02-10 16:26 UTC, olha-khomiakova commented on js/app/file-list-page/file-list-page/index.js
> +    });
Done.

2021-02-10 16:26 UTC, olha-khomiakova commented on js/app/services/state-service/state/index.js
> +  userDetails: new UserPreferences({name: '', id: '', rootFolderId: '', type: ''}),
Done.

2021-02-10 16:26 UTC, olha-khomiakova commented on js/app/services/state-service/state/index.js
> +  currentFolder: new FolderListModel({id: '', name: '', itemAmount: '', parentId: '', type: ''}),
Done.

2021-02-10 16:26 UTC, olha-khomiakova commented on js/tests/app/file-list-page/file-list-page/index.js
> +          ];
Done.

2021-02-10 22:51 UTC, dkalinin approved these changes
Please fix and merge.

2021-02-10 22:51 UTC, dkalinin commented on js/app/services/state-service/actions/index.js
> +export const ActionNames = {
Should be ActionName

2021-02-10 22:51 UTC, dkalinin commented on js/app/services/state-service/mutators/index.js
> +import {MutatorNames} from './mutator.js';
Should be MutatorName.

2021-02-10 22:51 UTC, dkalinin commented on js/tests/app/services/state-service/actions/index.js
> +    });
Actions return promises so this can be moved to then() instead of setTimeout() and done().

2021-02-11 13:33 UTC, olha-khomiakova commented on js/app/services/state-service/actions/index.js
> +export const ActionNames = {
Done.

2021-02-11 13:33 UTC, olha-khomiakova commented on js/app/services/state-service/mutators/index.js
> +import {MutatorNames} from './mutator.js';
Done.

2021-02-11 14:51 UTC, olha-khomiakova commented on js/tests/app/services/state-service/actions/index.js
> +    });
Done.

2021-02-11 16:19 UTC, merged